name: Auto Create PR

on:
  push:
    branches:
      - notes-sync

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: notes-sync
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug git
        run: |
          git status
          git branch -a

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-pr
          base: main
          delete-branch: true
          title: "Auto sync notes"
          body: "Auto PR from Obsidian Git"
