name: Auto Create PR

on:
  push:
    branches:
      - notes-sync   # hoặc user-a, user-b

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: notes-sync
          base: main
          title: "Auto sync notes"
          body: "Auto PR from Obsidian Git"
